on:
  push:
  pull_request:

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install node 21
        uses: actions/setup-node@v1
        with:
          node-version: 21
      - name: yarn install
        run: yarn install
      - name: eslint
        uses: icrawl/action-eslint@v1

